/* ══════════════════════════════════════════
   WEBCRAFT — EXPORTER
   Generates HTML, React JSX, or Tailwind
══════════════════════════════════════════ */

const Exporter = {
  _format: 'html',

  setFormat(fmt) {
    this._format = fmt;
    document.querySelectorAll('.etab').forEach(b =>
      b.classList.toggle('active', b.textContent.toLowerCase().includes(fmt === 'tailwind' ? 'tailwind' : fmt === 'react' ? 'react' : 'html'))
    );
    this._updatePreview();
  },

  open() {
    this._format = 'html';
    document.querySelectorAll('.etab').forEach((b, i) => b.classList.toggle('active', i === 0));
    this._updatePreview();
    document.getElementById('modal-export').classList.remove('hidden');
  },

  _updatePreview() {
    const pre = document.getElementById('export-preview');
    if (!pre) return;
    let code = '';
    try {
      if (this._format === 'html') code = this.generateHTML();
      else if (this._format === 'react') code = this.generateReact();
      else code = this.generateTailwind();
    } catch(e) {
      code = '// Error generating code: ' + e.message;
    }
    pre.textContent = code;
  },

  // ── GENERATE HTML + CSS ──
  generateHTML() {
    const name = State.projectName || 'Webcraft Project';
    const blocks = State.blocks.slice().sort((a, b) => a.y - b.y);
    const isDark = document.documentElement.getAttribute('data-theme') === 'dark';

    const bodyBg = isDark ? '#0F0F12' : '#F4F4F8';
    const textColor = isDark ? '#F0F0F8' : '#1A1A2E';

    // Generate CSS for fonts
    let css = `/* Generated by Webcraft */
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap');

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { font-family: 'DM Sans', sans-serif; }
body { background: ${bodyBg}; color: ${textColor}; -webkit-font-smoothing: antialiased; }
a { color: inherit; text-decoration: none; }
img { max-width: 100%; }
.wc-container { max-width: 1200px; margin: 0 auto; padding: 0 24px; }

`;

    // Collect unique styles
    const styleMap = {};
    blocks.forEach(b => {
      const cls = `wc-${b.type}-${b.id}`;
      styleMap[cls] = this._blockToCSS(b);
    });
    Object.entries(styleMap).forEach(([cls, style]) => {
      css += `.${cls} { ${style} }\n`;
    });

    // Generate HTML elements
    const bodyHTML = blocks.map(b => this._blockToHTML(b)).join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${this._escapeHtml(name)}</title>
  <style>
${css}
  </style>
</head>
<body>
${bodyHTML}

  <script>
    // Generated by Webcraft
    console.log('${this._escapeHtml(name)} - Built with Webcraft');
  <\/script>
</body>
</html>`;
  },

  _blockToHTML(block) {
    const p = block.props;
    const cls = `wc-${block.type}-${block.id}`;
    const style = `position:absolute;left:${block.x}px;top:${block.y}px;width:${block.w}px;height:${block.h}px;`;

    switch (block.type) {
      case 'heading':
        return `  <${p.tag||'h2'} class="${cls}" style="${style}font-size:${p.fontSize}px;font-weight:${p.fontWeight};text-align:${p.align};font-family:'Syne',sans-serif;">${this._escapeHtml(p.text)}</${p.tag||'h2'}>`;

      case 'text':
        return `  <p class="${cls}" style="${style}font-size:${p.fontSize}px;line-height:${p.lineHeight};text-align:${p.align};">${this._escapeHtml(p.text)}</p>`;

      case 'button':
        return `  <button class="${cls}" style="${style}background:${p.bg||'#6C63FF'};color:${p.color||'white'};border:none;border-radius:${p.radius||8}px;font-size:${p.fontSize||14}px;font-weight:600;cursor:pointer;font-family:'Syne',sans-serif;">${this._escapeHtml(p.text)}</button>`;

      case 'link':
        return `  <a href="${p.href||'#'}" class="${cls}" style="${style}color:${p.color||'#6C63FF'};text-decoration:underline;font-size:14px;">${this._escapeHtml(p.text)}</a>`;

      case 'image':
        return p.src
          ? `  <img src="${p.src}" alt="${this._escapeHtml(p.alt||'')}" class="${cls}" style="${style}object-fit:${p.objectFit||'cover'};border-radius:${p.radius||0}px;" />`
          : `  <!-- Image placeholder -->`;

      case 'input':
        return `  <input type="${p.type||'text'}" placeholder="${this._escapeHtml(p.placeholder||'')}" class="${cls}" style="${style}background:#1A1A24;border:1.5px solid rgba(255,255,255,0.1);border-radius:${p.radius||8}px;padding:10px 14px;color:inherit;font-size:14px;font-family:inherit;" />`;

      case 'textarea':
        return `  <textarea placeholder="${this._escapeHtml(p.placeholder||'')}" rows="${p.rows||4}" class="${cls}" style="${style}background:#1A1A24;border:1.5px solid rgba(255,255,255,0.1);border-radius:${p.radius||8}px;padding:10px 14px;color:inherit;font-size:14px;font-family:inherit;resize:vertical;"></textarea>`;

      case 'navbar':
        const navLinks = (p.links||'').split('\n').filter(Boolean).map(l => `<a href="#" style="font-size:13px;color:inherit;opacity:0.8;transition:opacity 0.2s;" onmouseover="this.style.opacity=1" onmouseout="this.style.opacity=0.8">${this._escapeHtml(l.trim())}</a>`).join('');
        return `  <nav class="${cls}" style="${style}background:${p.bg||'rgba(15,15,18,0.9)'};backdrop-filter:blur(20px);display:flex;align-items:center;justify-content:space-between;padding:0 24px;${p.sticky?'position:sticky;top:0;z-index:100;':''}">
    <div style="font-family:'Syne',sans-serif;font-weight:800;font-size:18px;">${this._escapeHtml(p.logo||'Brand')}</div>
    <div style="display:flex;gap:24px;">${navLinks}</div>
    ${p.showBtn ? `<button style="background:#6C63FF;color:white;border:none;border-radius:8px;padding:8px 18px;font-size:13px;font-weight:600;cursor:pointer;font-family:inherit;">${this._escapeHtml(p.btnText||'Get Started')}</button>` : ''}
  </nav>`;

      case 'hero':
        return `  <section class="${cls}" style="${style}background:${p.bg||'linear-gradient(135deg,#6C63FF,#3ECFCF)'};display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;padding:48px 40px;text-align:center;">
    <div style="font-size:11px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:rgba(255,255,255,0.7);background:rgba(255,255,255,0.15);padding:4px 14px;border-radius:99px;">${this._escapeHtml(p.tag||'')}</div>
    <h1 style="font-family:'Syne',sans-serif;font-weight:800;font-size:clamp(28px,5vw,52px);color:white;line-height:1.1;">${this._escapeHtml(p.title||'')}</h1>
    <p style="font-size:16px;color:rgba(255,255,255,0.75);max-width:560px;line-height:1.6;">${this._escapeHtml(p.subtitle||'')}</p>
    <div style="display:flex;gap:12px;margin-top:8px;">
      <button style="background:white;color:#6C63FF;border:none;border-radius:99px;padding:12px 28px;font-weight:700;cursor:pointer;font-family:inherit;">${this._escapeHtml(p.btnText||'Get Started')}</button>
      <button style="background:rgba(255,255,255,0.15);color:white;border:none;border-radius:99px;padding:12px 28px;font-weight:600;cursor:pointer;font-family:inherit;">${this._escapeHtml(p.btn2Text||'Learn More')}</button>
    </div>
  </section>`;

      case 'card':
        return `  <div class="${cls}" style="${style}background:#1C1C26;border:1.5px solid rgba(255,255,255,0.08);border-radius:16px;padding:20px;display:flex;flex-direction:column;gap:10px;">
    <h3 style="font-family:'Syne',sans-serif;font-weight:700;font-size:18px;">${this._escapeHtml(p.title||'')}</h3>
    <p style="font-size:13px;color:rgba(255,255,255,0.6);line-height:1.5;">${this._escapeHtml(p.body||'')}</p>
    ${p.showBtn ? `<button style="background:#6C63FF;color:white;border:none;border-radius:8px;padding:8px 16px;font-size:13px;font-weight:600;cursor:pointer;width:fit-content;font-family:inherit;">${this._escapeHtml(p.btnText||'Learn More')}</button>` : ''}
  </div>`;

      case 'divider':
        return `  <hr class="${cls}" style="${style}border:none;height:${p.thickness||1}px;background:rgba(255,255,255,0.1);" />`;

      case 'badge':
        return `  <span class="${cls}" style="${style}display:inline-flex;align-items:center;background:rgba(108,99,255,0.15);color:#8F88FF;border-radius:99px;padding:4px 12px;font-size:11px;font-weight:700;">${this._escapeHtml(p.text||'Badge')}</span>`;

      case 'progress':
        return `  <div class="${cls}" style="${style}display:flex;flex-direction:column;gap:6px;padding:10px 14px;">
    <div style="display:flex;justify-content:space-between;font-size:11px;font-weight:600;opacity:0.7;"><span>${this._escapeHtml(p.label||'Progress')}</span><span>${p.value||0}%</span></div>
    <div style="height:6px;background:rgba(255,255,255,0.08);border-radius:99px;overflow:hidden;"><div style="width:${p.value||0}%;height:100%;background:linear-gradient(90deg,#6C63FF,#3ECFCF);border-radius:99px;"></div></div>
  </div>`;

      case 'rect':
        return `  <div class="${cls}" style="${style}background:${p.bg||'rgba(108,99,255,0.15)'};border-radius:${p.radius||8}px;${p.border?`border:${p.borderWidth||1}px solid ${p.border};`:''}opacity:${(p.opacity||100)/100};"></div>`;

      case 'circle':
        return `  <div class="${cls}" style="${style}background:${p.bg||'rgba(108,99,255,0.15)'};border-radius:50%;"></div>`;

      case 'spacer':
        return `  <div class="${cls}" style="${style}"></div>`;

      case 'footer':
        return `  <footer class="${cls}" style="${style}background:#0C0C10;padding:40px 32px;display:flex;flex-direction:column;gap:24px;">
    <div style="font-family:'Syne',sans-serif;font-weight:800;font-size:20px;">${this._escapeHtml(p.brand||'Brand')}</div>
    <div style="height:1px;background:rgba(255,255,255,0.08);"></div>
    <p style="font-size:12px;color:rgba(255,255,255,0.4);">${this._escapeHtml(p.copyright||'')}</p>
  </footer>`;

      case 'cta':
        return `  <section class="${cls}" style="${style}background:linear-gradient(135deg,rgba(108,99,255,0.2),rgba(62,207,207,0.2));border:1.5px solid rgba(108,99,255,0.3);border-radius:24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;padding:40px;text-align:center;">
    <h2 style="font-family:'Syne',sans-serif;font-weight:800;font-size:28px;">${this._escapeHtml(p.title||'')}</h2>
    <p style="color:rgba(255,255,255,0.6);font-size:14px;">${this._escapeHtml(p.subtitle||p.sub||'')}</p>
    <button style="background:#6C63FF;color:white;border:none;border-radius:99px;padding:12px 32px;font-weight:700;cursor:pointer;font-family:inherit;">${this._escapeHtml(p.btnText||'Get Started')}</button>
  </section>`;

      case 'icon':
        return `  <div class="${cls}" style="${style}display:flex;align-items:center;justify-content:center;font-size:${p.size||32}px;">${p.emoji||'⭐'}</div>`;

      case 'label':
        return `  <span class="${cls}" style="${style}font-size:${p.fontSize||11}px;font-weight:700;letter-spacing:${p.letterSpacing||'0.06em'};text-transform:${p.uppercase?'uppercase':'none'};color:rgba(255,255,255,0.5);">${this._escapeHtml(p.text||'Label')}</span>`;

      case 'container':
      case 'section':
      case 'row':
      case 'column':
      case 'grid':
        return `  <div class="${cls}" style="${style}"><!-- ${block.type} --></div>`;

      default:
        return `  <!-- ${block.type} -->`;
    }
  },

  _blockToCSS(block) {
    return `opacity:${(block.opacity||100)/100};`;
  },

  _escapeHtml(str) {
    return (str || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  },

  // ── GENERATE REACT ──
  generateReact() {
    const name = (State.projectName || 'WebcraftApp').replace(/[^a-zA-Z0-9]/g, '');
    const blocks = State.blocks.slice().sort((a, b) => a.y - b.y);
    const components = blocks.map(b => this._blockToJSX(b)).join('\n      ');

    return `// Generated by Webcraft
import React from 'react';

export default function ${name}() {
  return (
    <div style={{ position: 'relative', minHeight: '100vh', background: '#0F0F12', color: '#F0F0F8', fontFamily: "'DM Sans', sans-serif" }}>
      ${components}
    </div>
  );
}`;
  },

  _blockToJSX(block) {
    const p = block.props;
    const style = `{{ position: 'absolute', left: ${block.x}, top: ${block.y}, width: ${block.w}, height: ${block.h} }}`;

    switch (block.type) {
      case 'heading': return `<h${p.tag?p.tag.replace('h',''):'2'} style=${style}>${p.text}</h${p.tag?p.tag.replace('h',''):'2'}>`;
      case 'text': return `<p style=${style}>${p.text}</p>`;
      case 'button': return `<button style=${style} onClick={() => {}}>${p.text}</button>`;
      case 'image': return p.src ? `<img src="${p.src}" alt="${p.alt||''}" style=${style} />` : `{/* Image */}`;
      case 'input': return `<input type="${p.type||'text'}" placeholder="${p.placeholder||''}" style=${style} />`;
      case 'card': return `<div style=${style}><h3>${p.title}</h3><p>${p.body}</p></div>`;
      default: return `{/* ${block.type} */}`;
    }
  },

  // ── GENERATE TAILWIND ──
  generateTailwind() {
    const blocks = State.blocks.slice().sort((a, b) => a.y - b.y);
    const items = blocks.map(b => {
      const p = b.props;
      switch (b.type) {
        case 'heading': return `  <h2 class="text-4xl font-extrabold text-white">${p.text}</h2>`;
        case 'text': return `  <p class="text-gray-400 leading-relaxed">${p.text}</p>`;
        case 'button': return `  <button class="bg-indigo-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-indigo-700 transition">${p.text}</button>`;
        case 'card': return `  <div class="bg-gray-800 rounded-2xl p-6 border border-gray-700">\n    <h3 class="text-lg font-bold text-white mb-2">${p.title}</h3>\n    <p class="text-gray-400 text-sm">${p.body}</p>\n  </div>`;
        case 'navbar': return `  <nav class="flex items-center justify-between px-8 py-4 bg-gray-900 sticky top-0 z-50">\n    <span class="font-extrabold text-xl text-white">${p.logo}</span>\n  </nav>`;
        default: return `  <!-- ${b.type} -->`;
      }
    }).join('\n');

    return `<!-- Generated by Webcraft (Tailwind CSS) -->
<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="UTF-8">
  <title>${State.projectName}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body class="bg-gray-950 text-white min-h-screen">
${items}
</body>
</html>`;
  },

  // ── COPY & DOWNLOAD ──
  copyCode() {
    const pre = document.getElementById('export-preview');
    navigator.clipboard.writeText(pre.textContent).then(() => App.toast('Code copied!', 'success'));
  },

  download() {
    const code = document.getElementById('export-preview').textContent;
    const ext = this._format === 'react' ? 'jsx' : 'html';
    const name = (State.projectName || 'webcraft').replace(/\s+/g, '-').toLowerCase();
    const blob = new Blob([code], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${name}.${ext}`;
    a.click();
    App.toast(`Downloaded ${name}.${ext}`, 'success');
  }
};
